# Generated by Django 2.1 on 2018-09-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.TextField()),
                ('board_url', models.URLField(max_length=300)),
                ('board_text', models.TextField()),
            ],
        ),
    ]
