# Generated by Django 2.1 on 2018-09-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
