# Generated by Django 2.1 on 2018-09-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_board_board_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_id',
        ),
    ]
