# Generated by Django 2.1 on 2018-09-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0003_remove_board_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
