# Generated by Django 2.1 on 2018-09-09 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0004_board_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
