# Generated by Django 2.1 on 2018-09-09 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0005_board_board_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='board_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='board_date',
            field=models.TextField(),
        ),
    ]
