# Generated by Django 2.1 on 2018-09-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20180909_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='board_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
